title: 西北大学经济管理学院筑牢中华民族共同体意识语料库
baseurl: ""
url: "https://你的用户名.github.io"

plugins:
  - jekyll-search      # 搜索功能
  - jekyll-feed        # 生成 RSS 订阅（可选）

search:
  collections: ['corpus']       # 索引的集合名称（对应 _posts/corpus 目录）
  fields: ['title', 'content', 'image', 'video']  # 索引字段
  output: true                   # 生成 search.json 文件

defaults:
  - scope:
      path: "_posts/corpus"      # 对 corpus 目录下的文件应用默认配置
    values:
      layout: "corpus"           # 默认使用 corpus.html 模板
      category: "corpus"         # 默认分类为 corpus

